# Generated by Django 3.0.5 on 2020-04-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_subcategoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'descripcion')},
        ),
    ]
